const CONTINENT_MAP = {
  // ---- North America ----
  "United States of America": "North America",
  "Canada": "North America",
  "Mexico": "North America",
  "Guatemala": "North America",
  "Belize": "North America",
  "Honduras": "North America",
  "El Salvador": "North America",
  "Nicaragua": "North America",
  "Costa Rica": "North America",
  "Panama": "North America",
  "Cuba": "North America",
  "Haiti": "North America",
  "Dominican Rep.": "North America",
  "Jamaica": "North America",
  "Bahamas": "North America",
  "Trinidad and Tobago": "North America",
  "Antigua and Barb.": "North America",
  "Barbados": "North America",
  "Dominica": "North America",
  "Grenada": "North America",
  "Saint Lucia": "North America",
  "St. Kitts and Nevis": "North America",
  "St. Vin. and Gren.": "North America",
  "Puerto Rico": "North America",
  "Greenland": "North America",

  // ---- South America ----
  "Brazil": "South America",
  "Argentina": "South America",
  "Chile": "South America",
  "Peru": "South America",
  "Colombia": "South America",
  "Venezuela": "South America",
  "Ecuador": "South America",
  "Bolivia": "South America",
  "Paraguay": "South America",
  "Uruguay": "South America",
  "Guyana": "South America",
  "Suriname": "South America",
  "Falkland Is.": "South America",

  // ---- Europe ----
  "Iceland": "Europe",
  "Norway": "Europe",
  "Sweden": "Europe",
  "Finland": "Europe",
  "Denmark": "Europe",
  "United Kingdom": "Europe",
  "Ireland": "Europe",
  "Netherlands": "Europe",
  "Belgium": "Europe",
  "Luxembourg": "Europe",
  "France": "Europe",
  "Spain": "Europe",
  "Portugal": "Europe",
  "Andorra": "Europe",
  "Germany": "Europe",
  "Switzerland": "Europe",
  "Liechtenstein": "Europe",
  "Austria": "Europe",
  "Italy": "Europe",
  "Vatican": "Europe",
  "San Marino": "Europe",
  "Monaco": "Europe",
  "Malta": "Europe",
  "Poland": "Europe",
  "Czechia": "Europe",
  "Slovakia": "Europe",
  "Hungary": "Europe",
  "Slovenia": "Europe",
  "Croatia": "Europe",
  "Bosnia and Herz.": "Europe",
  "Serbia": "Europe",
  "Montenegro": "Europe",
  "Kosovo": "Europe",
  "Albania": "Europe",
  "North Macedonia": "Europe",
  "Macedonia": "Europe",
  "Greece": "Europe",
  "Bulgaria": "Europe",
  "Romania": "Europe",
  "Moldova": "Europe",
  "Ukraine": "Europe",
  "Belarus": "Europe",
  "Lithuania": "Europe",
  "Latvia": "Europe",
  "Estonia": "Europe",
  "Russia": "Europe",

  // ---- Africa ----
  "Morocco": "Africa",
  "Algeria": "Africa",
  "Tunisia": "Africa",
  "Libya": "Africa",
  "Egypt": "Africa",
  "Western Sahara": "Africa",
  "W. Sahara": "Africa",
  "Mauritania": "Africa",
  "Mali": "Africa",
  "Niger": "Africa",
  "Chad": "Africa",
  "Sudan": "Africa",
  "S. Sudan": "Africa",
  "Eritrea": "Africa",
  "Djibouti": "Africa",
  "Ethiopia": "Africa",
  "Somalia": "Africa",
  "Somaliland": "Africa",
  "Kenya": "Africa",
  "Uganda": "Africa",
  "Rwanda": "Africa",
  "Burundi": "Africa",
  "Tanzania": "Africa",
  "Senegal": "Africa",
  "Gambia": "Africa",
  "Guinea-Bissau": "Africa",
  "Guinea": "Africa",
  "Sierra Leone": "Africa",
  "Liberia": "Africa",
  "Côte d'Ivoire": "Africa",
  "Ivory Coast": "Africa",
  "Ghana": "Africa",
  "Togo": "Africa",
  "Benin": "Africa",
  "Burkina Faso": "Africa",
  "Nigeria": "Africa",
  "Cameroon": "Africa",
  "Eq. Guinea": "Africa",
  "Gabon": "Africa",
  "Congo": "Africa",
  "Dem. Rep. Congo": "Africa",
  "Central African Rep.": "Africa",
  "Angola": "Africa",
  "Zambia": "Africa",
  "Malawi": "Africa",
  "Mozambique": "Africa",
  "Zimbabwe": "Africa",
  "Botswana": "Africa",
  "Namibia": "Africa",
  "South Africa": "Africa",
  "Lesotho": "Africa",
  "Swaziland": "Africa",
  "eSwatini": "Africa",
  "Madagascar": "Africa",
  "Cabo Verde": "Africa",
  "São Tomé and Principe": "Africa",
  "Seychelles": "Africa",
  "Comoros": "Africa",
  "Mauritius": "Africa",

  // ---- Asia ----
  "Turkey": "Asia",
  "Cyprus": "Asia",
  "N. Cyprus": "Asia",
  "Syria": "Asia",
  "Lebanon": "Asia",
  "Israel": "Asia",
  "Palestine": "Asia",
  "Jordan": "Asia",
  "Iraq": "Asia",
  "Iran": "Asia",
  "Saudi Arabia": "Asia",
  "Yemen": "Asia",
  "Oman": "Asia",
  "United Arab Emirates": "Asia",
  "Qatar": "Asia",
  "Kuwait": "Asia",
  "Bahrain": "Asia",
  "Georgia": "Asia",
  "Armenia": "Asia",
  "Azerbaijan": "Asia",
  "Kazakhstan": "Asia",
  "Uzbekistan": "Asia",
  "Turkmenistan": "Asia",
  "Tajikistan": "Asia",
  "Kyrgyzstan": "Asia",
  "Afghanistan": "Asia",
  "Pakistan": "Asia",
  "India": "Asia",
  "Nepal": "Asia",
  "Bhutan": "Asia",
  "Bangladesh": "Asia",
  "Sri Lanka": "Asia",
  "Maldives": "Asia",
  "China": "Asia",
  "Mongolia": "Asia",
  "North Korea": "Asia",
  "South Korea": "Asia",
  "Korea": "Asia",
  "Japan": "Asia",
  "Taiwan": "Asia",
  "Myanmar": "Asia",
  "Laos": "Asia",
  "Thailand": "Asia",
  "Cambodia": "Asia",
  "Vietnam": "Asia",
  "Malaysia": "Asia",
  "Brunei": "Asia",
  "Singapore": "Asia",
  "Indonesia": "Asia",
  "Philippines": "Asia",
  "Timor-Leste": "Asia",

  // ---- Oceania ----
  "Australia": "Oceania",
  "New Zealand": "Oceania",
  "Papua New Guinea": "Oceania",
  "Fiji": "Oceania",
  "Solomon Is.": "Oceania",
  "Vanuatu": "Oceania",
  "New Caledonia": "Oceania",
  "Nauru": "Oceania",
  "Palau": "Oceania",
  "Marshall Is.": "Oceania",
  "Micronesia": "Oceania",
  "Kiribati": "Oceania",
  "Tonga": "Oceania",
  "Samoa": "Oceania",

  // ---- Antarctica ----
  "Antarctica": "Antarctica",
  "Fr. S. Antarctic Lands": "Antarctica",
}

const ALIASES = {
  "usa": "United States of America",
  "us": "United States of America",
  "u.s.": "United States of America",
  "u.s.a.": "United States of America",
  "united states": "United States of America",
  "america": "United States of America",
  "uk": "United Kingdom",
  "u.k.": "United Kingdom",
  "great britain": "United Kingdom",
  "britain": "United Kingdom",
  "england": "United Kingdom",
  "scotland": "United Kingdom",
  "wales": "United Kingdom",
  "uae": "United Arab Emirates",
  "emirates": "United Arab Emirates",
  "holland": "Netherlands",
  "the netherlands": "Netherlands",
  "czech republic": "Czechia",
  "czech": "Czechia",
  "south korea": "South Korea",
  "s. korea": "South Korea",
  "korea": "South Korea",
  "north korea": "North Korea",
  "burma": "Myanmar",
  "ivory coast": "Côte d'Ivoire",
  "cote d'ivoire": "Côte d'Ivoire",
  "drc": "Dem. Rep. Congo",
  "dr congo": "Dem. Rep. Congo",
  "democratic republic of the congo": "Dem. Rep. Congo",
  "congo": "Congo",
  "swaziland": "eSwatini",
  "macedonia": "North Macedonia",
  "dominican republic": "Dominican Rep.",
  "bosnia": "Bosnia and Herz.",
  "east timor": "Timor-Leste",
  "russia": "Russia",
  "russian federation": "Russia",
  "vietnam": "Vietnam",
  "viet nam": "Vietnam",
}

export const SEED = [
  "United States of America", "Canada", "Mexico", "Cuba",
  "United Kingdom", "Ireland", "France", "Spain", "Portugal",
  "Italy", "Germany", "Netherlands", "Switzerland", "Austria",
  "Czechia", "Greece", "Croatia",
  "Morocco", "Egypt", "South Africa", "Tanzania",
  "Japan", "Thailand", "Vietnam", "Indonesia", "India", "Turkey",
  "Australia", "New Zealand", "Brazil", "Argentina", "Peru", "Chile",
]

export const WORLD_TOTAL = 195
export const CONTINENT_ORDER = ["Africa", "Asia", "Europe", "North America", "South America", "Oceania"]
export { CONTINENT_MAP, ALIASES }
export const continentOf = (name) => CONTINENT_MAP[name] || null
export const resolveAlias = (q) => ALIASES[q.trim().toLowerCase()] || null
